spring:
  application:
    name: csc1106
  datasource:
    url: jdbc:mysql://learnzenith.mysql.database.azure.com:3306/webprogDB?ssl-mode=REQUIRED
    username: grp7
    password: Naim6oo3!!!!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

azure:
  storage:
    connection-string: DefaultEndpointsProtocol=https;AccountName=learnzenithblob;AccountKey=AImtsIhXXZHqqyeCr/uD/QuCy+JyvYUDwE1feJqoMtBYnsxu48QGVW6j7pAnKwfakT1qNkZqKoA9+ASt0lTZWQ==
    container-name: courseuploads
